ALTER TYPE "AlertType" ADD VALUE IF NOT EXISTS 'INCIDENT_OVERDUE_7D';
ALTER TYPE "AlertType" ADD VALUE IF NOT EXISTS 'INCIDENT_OVERDUE_14D';
ALTER TYPE "AlertType" ADD VALUE IF NOT EXISTS 'INCIDENT_OVERDUE_21D';
